//! Dependency injection container.
#![cfg_attr(feature = "traits", feature(unsize))]

/// Allow `::studiole_di::` paths generated by derive macros to resolve within this crate.
extern crate self as studiole_di;

#[cfg(feature = "async")]
mod r#async;
mod extensions;
pub mod prelude;
mod schema;
mod service_builder;
mod service_provider;
mod traits;

#[cfg(feature = "async")]
pub use r#async::FromProviderAsync;
pub use schema::FromProvider;
pub use service_provider::{ResolveError, ServiceProvider};
